# Use an official Python image as the base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the Python application source code into the container
COPY app.py .

# Run the Python application
CMD ["python", "app.py"]
